### PR TITLE
attempts to improve the DLM stan model

### PR DESCRIPTION
**Pull request by dantonnoriega**
thanks for the amazing examples and lectures. in this pull request, you'll find 2 scripts (1 R, 1 Stan) of my attempts to run a DLM model in Stan after I found the provided model and scripts to produce odd results.

The Stan script was my attempt to reparameterize the DLM model so that the sampling produces less divergent transitions. I still am not sure if its accurate but, upon looking at plots, seems pretty good.

Screen Shot 2019-11-21 at 3 24 30 PM
Screen Shot 2019-11-21 at 3 24 48 PM

### CODE REVIEW

**Comment by eeholmes** [comment]
Hi Danton,

Thanks so much for pointing out the issue with the dlm fit using atsar. The fit is definitely having problems.  I was able to get your dlm-vec.stan model to work and replicate your figures. However, the dlm-vec2.stan is giving odd results (image below).

Note that MARSS and stan are fitting the same models so should give the same results. What you are plotting for MARSS is rather different than what you are plotting for the stan model. For stan you are plotting the expected value of y(t) conditioned on all the data (1 to T) while for MARSS, you are plotting the expected value of y(t) conditioned on the data up to t-1. To plot what you are plotting for the stan model use this code

```
layout(matrix(1:2))
ylims=c(min(fore.mean-2*sqrt(fore.var)),max(fore.mean+2*sqrt(fore.var)))
plot(years, t(dat), type="p", pch=16, ylim=ylims,
     col="blue", xlab="", ylab="Logit(s)", xaxt="n")
lines(years, fitted(dlm1), type="l", xaxt="n", ylab="", lwd=3)
```

Notice the `fitted(dlm1)` rather and the "forecast" values. The forecast values are using y(t) conditioned on 1:(t-1).  `fitted(dlm1)` is returning alpha(t|1:T) + beta(t|1:T)*c(t) which is what you are returning from your stan model: expected value of y(t) using the alpha and beta smoothed states (smoothed = conditioned on all the data).

I'll dig into atsar and your stan code more to figure out what is going on.  DLM models can be a bit wonky to fit because of ridges in the likelihood surface.

Regards,

Eli

dlm-compare

marss-stan

**Comment by eeholmes** [comment]
Here is better code for plotting MARSS vs stan model. 

```
layout(matrix(1:2))
ylims=c(min(fore.mean-2*sqrt(fore.var)),max(fore.mean+2*sqrt(fore.var)))
plot(years, t(dat), type="p", pch=16, ylim=ylims,
     col="blue", xlab="", ylab="Logit(s)", xaxt="n")
tmp <- broom::augment(dlm1, interval="confidence")
polygon(x = xx, y = c(tmp$.conf.low, rev(tmp$.conf.up)), col = scales::alpha('gray', .5), border = NA)
lines(years, tmp$.fitted, type="l", xaxt="n", ylab="")

title("MARSS using fitted(dlm1)")
#
pars = extract(mod0)
fc <- apply(pars$F_Theta, 2, mean)
fc_lb <- apply(pars$F_Theta, 2, quantile, 0.01)
fc_ub <- rev(apply(pars$F_Theta, 2, quantile, 0.99))
plot(x = years, y = y, pch = 16, col="blue", ylim = ylims)
polygon(x = xx, y = c(fc_lb, fc_ub), col = scales::alpha('gray', .5), border = NA)
lines(x = years, y = fc, type="l")
title("dlm-vec2.stan")
```

marss-stan

**Review by ericward-noaa — APPROVED** [review]

**Comment by ericward-noaa** [comment]
Agreed - thanks Danton. I'll look at this later as well. There's a few other things with the code that I've been meaning to clean up before creating a new release. Thanks for the help!

**Comment by dantonnoriega** [comment]
Feel free to delete dlm-vec2.stan. It should have been deleted in the most recent push. Also odd because i actually replaced dlm-vec.stan with dlm-vec2.stan code---they should have been the same!

**Pull request merged**
